
### General -------------------

baseurl: https://example.org
title: Kat Millage
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: ''
googleAnalytics: ''
paginate: 10

### Menu Layout -------------------

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
      
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2
      
    - identifier: research
      name: Research
      url: /research/
      weight: 3
      
    - identifier: about
      name: About Me
      url: /about/
      weight: 4
      
    - identifier: photography
      name: Photography
      url: 'https://katmillage.smugmug.com/'
      weight: 4  
      
  topbar:
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/kmillage
      weight: 1
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: https://twitter.com/katmillage?lang=en
      weight: 2
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:millagek@gmail.com
      weight: 3
      
### Parameters -------------------

params:

  # Don't know where this goes...  
  author: DevCows

  # Section 1 - Top Bar: dark grey banner above menu
  topbar:
    enable: yes
    text: ""
    # "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n
    #   \     <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i
    #   class=\"fas fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i
    #   class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
    
  # Section 2 - Menu Bar  
  
  # Section 3 - Photo Carousel    
  carousel:
    enable: no
    
  # Section 4 - Features (OFF)
  features:
    enable: no
    
  # Section 5 - Testimonials (OFF)
  testimonials:
    enable: no
    subtitle: ''
    title: ''
    
  # Section 6 - See More
  see_more:
    enable: yes
    icon: img/logo-small.png
    link_text: Visit My Photography Site
    link_url: 'https://katmillage.smugmug.com/'
    subtitle: "Welecome to my website! I'm a researcher with the Environmental Market Solutions Lab (emLab) at UCSB.
    This site is a place for me to share materials related to my professional activities in the realms of fisheries management and data science. 
    If you're interested in my photogography, please visit my other site!"   
    title: "Kat Millage"
  style: default  
  
  # Section 7 - Recent Posts  
  recent_posts:
    enable: yes
    subtitle: Pellentesque habitant morbi tristique senectus et netus et malesuada
      fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
      tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
      ultricies mi vitae est. Mauris placerat eleifend leo.
    title: From My Blog  
    
  # Section 8 - Client carousel (OFF) 
  clients:
    enable: no
    subtitle: ''
    title: ''
  
  # Section 8 - Footer: contains three sections (About Us, Recent Posts, Contact)    
  about_us: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
    fames ac turpis egestas.</p>
  address: "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\n        <br>13/25
    New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>England\n
    \       <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
    
  # Copyright (footer)
  copyright: Copyright (c) 2021, Kat Millage; all rights reserved.
  
  
  # Other options
  contact_form_ajax: no
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by devcows using hugo
  defaultKeywords:
    - devows
    - hugo
    - go
  enableGoogleMaps: yes
  facebook_site: ''
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  longitude: '-77.028333'
  mainSections: blog
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
    
    
Permalinks:
  blog: /blog/:year/:month/:day/:filename/
