---
title: "WTO must ban harmful fisheries subsidies"
author: "Kat Millage"
description: "New letter published in Science!"
date: 2021-10-28T21:13:14-05:00
categories: ["Publications"]
tags: []
images: [src: "/blog/2021-10-28-wto-must-ban-subsidies/header.jpg"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

### About the Paper 

In a letter just published in Science, I joined 295 other hundred scientists from 255 institutions in 46 countries to ask members of the World Trade Organization (WTO) to ban harmful fisheries subsidies at the 12th Ministerial Conference. Spearheaded by Dr. Rashid Sumaila at the University of British Colombia, this letter entitled ["WTO must ban harmful fisheries subsidies"](https://doi.org/10.1126/science.abm1680) reiterates how the WTO is in a unique position to ban harmful fisheries subsidies and thus help to curb overfishing, biodiversity degradation and loss, and CO2 emissions, and to safeguard food and livelihoods.

### Key Messages

An effective agreement to reform fisheries subsidies should remove subsidies that cause harm by lowering the cost of fuel and those that support new vessel construction and provide price support to keep market prices artificially high. It should also remove subsidies to distant water fishing fleets. The WTO should allow special and differential treatment for small scale fishers that use non-destructive gears or those that fish for subsistence, but only if subsidies are decoupled from incentivizing overfishing in these fisheries, and they must ensure accountability and require transparent data documentation and enforcement.  

### Media 

The following sources provide coverage of our letter:

* October 29, 2021 - EurekAlert: [Nearly 300 scientists ask the WTO to ban harmful fisheries subsidies](https://www.eurekalert.org/news-releases/933170)
* October 29, 2021 - Mirage News: [UWA scientists join international push to ban harmful fisheries subsidies](https://www.miragenews.com/uwa-scientists-join-international-push-to-ban-662356/)
* October 29, 2021 - Phys Org: [Scientists join international push to ban harmful fisheries subsidies](https://phys.org/news/2021-10-scientists-international-fisheries-subsidies.html)
* November 1, 2021 - Lab Manager: [Nearly 300 Scientists Ask the WTO to Ban Harmful Fisheries Subsidies](https://www.labmanager.com/news/nearly-300-scientists-ask-the-wto-to-ban-harmful-fisheries-subsidies-26988)